### PR TITLE
Update telemetry to 0.8.0

### PR DESCRIPTION
**Pull request by fbricon**
To restrict sending startup events to 1 daily only

Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Review by msivasubramaniaan — APPROVED** [review]
LGTM

**Comment by hlshen** [comment]
Any chance we can merge this?

**Comment by msivasubramaniaan** [comment]
@fbricon please rebase and resolve the conflicts

**Comment by fbricon** [comment]
@msivasubramaniaan please try it again

**Pull request merged**
