### PR TITLE
Enable yaml validation for .travis.yml by default

### PR DESCRIPTION
**Pull request by fbricon**
Blame @gorkem https://twitter.com/GorkemErcan/status/933439972799021057 :-)

### CODE REVIEW

**Comment by fbricon** [comment]
Actually it might not be such a good idea:
screen shot 2017-11-22 at 5 40 08 pm

with:

```yaml
language: java
sudo: false
script: 
- 'mvn -Pserver-distro clean verify'
# - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'
jdk:
- oraclejdk8
addons:
  sonarqube: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  - $HOME/.gradle/
env:
  global:
    secure: X+snbuGeonQZa/7sHkRDxSK5+tvYvXTxht9fGaY8sLvVnqvLmY67j3ZMRRGWrfar0pIY6zzPYuqSycA7XXhD8QUyhDVWSy8xCgfqUdG2QyjoYjJjyA6UvZmqoNQONT412w5qoaO7q5lGgxUOIU9b8TJRxkCszpYCyLhFgolmaUUzQRx2X8+s5vkTuAITDkD7XbKEyWmRd88n4g1P6MuvoshIaqUCXIT+5E3RGiP/EIGmdvdXyild1ViHf8+EVXQWUDwT+VMc1NNnSYRm7A8yMq3gW5MMp5SETMySP75HQubf+azuZJ175oucqFlOWI6N8NHsP/u1L7lagdsRGlFsr7/vYEtyQABF8EYXZD6FcROsUIWm9d7ExhNDHo5XRwBVaEts1JW2bJYO4Jrs6I/Bv00tD56qfuj6RoNNkfvHmIoCkgIHbwHzHG5zEiGpjN6rBODKohCTsw6UrpgWk6IbUBcE/7sgH4rKQOyktwwLIdYozSO6QttV38EcqRT2pS4vVBEhJSD7h+7Xr/bA0xC8KUGEsKcvuLWrA+Z27BTtZxevwJ7IjIcfNyMjUKMtQyxmd/jp/OfALHyLs65qK35W1Tkmawe82xBS9++2/+/EpeqRCr8N9eIlgi6S2LbNkKHqMKIZxRFutD6zMe7Z3oCt4NF7sEzqmmkCNtB35ohZ68U=
deploy:
  provider: bintray
  file: ./descriptor.json
  user: gorkem
  key:
    secure: e9bgz2HPEzbwLv6F5b+JW0164LZWH5SxOesf2lsvjOK0+flzrqDdHiwGdN+1ND0E1Qc4eLNmhbi1fYblfzzIcWgtXuW5nZ0wdz08WlR1NrlUZ+u85ol9/7PFdbZSWqgDcQ7JPjrJ+pNozy7bV9jbEq7XU2ziRJQgicoIxRYe+AoJoPD3YC9TIvMW6TwtArCgWZndaqvoq9JLJqVJ5zUGeocbygaEyZmItUNyhYMUUkuFrtGChAMHY074dC0KEza7nCwXhBwg4hC1CZ7nm89p4PFSwvVQY3/ZaQrwFUqNyg8J42/DPzjkSyyycv89ylZnoCzAY+S8S5nIj33LANwG3bEhQlKVqlgzQd80mb7EvOHccWOkj/8xLvRCsD4kVbfrUJM4JVDjPO+DEtSFq5ptOiY4zc0XEkeWFvstmRIVOvpukS76ZbF/AyTMvEDHHVNIC7mZhegTFOK2+RFMGXAx4A8Ry+RE59EL0qInQlMQ2+eCPmVcOolEzMDVjig5EvZLIfmEUPdROUL9vFenlGQ1vBwg2ZYSnzO8ENHbruoLl9rAYOtRFezTodVvqFvLSlQGoKW/DfSAq8sCBccG8XbmQC5RHCgmN9Hck3QGs6O+ovEOl162LSTgtTTwdG3HY5CT+rsvqvyHEZ+7aE5gUd4yQESDZAHrdsOmXIA3cHb+TGw=

```

**Comment by gorkem** [comment]
I think this should use the yamlValidation contribution point which works the same way as https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation

**Comment by JPinkney** [comment]
I think its better suited through the yamlValidation contribution point as well. However, there was a request through an [issue](https://github.com/redhat-developer/yaml-language-server/issues/15) by the creator of the php language server that asked for the server to pull yaml schemas from the json schema store directly via the [api](http://schemastore.org/api/json/catalog.json). I have it currently implemented and it would make it a lot easier for users working with common yaml files

**Comment by JPinkney** [comment]
I've opened a PR for this redhat-developer/yaml-language-server/pull/23. The question is whether or not we want to proceed with this. I've found one issue with the appveyor schema on the store that makes it incompatible with autocompletion and @fbricon found an issue with the travis schema. I've got the appveyor schema working now with [this](https://gist.github.com/JPinkney/a2ce9c6a04a72422e55c8b07844a763b) but i'm not so sure if we can always easily provide support for the schemas from the schema store.

**Comment by fbricon** [comment]
Issue is being taken care of on the server side, so closing.

**Comment by felixfbecker** [comment]
I agree that this should definitely be fixed by reading schemas from jsonschemastore. Otherwise we will get into a situation where we have too many schemas to this language server and every update of the schema requires an update of the extension. While to improve jsonschemastore, anyone can do a PR there and the extension will get the latest schema - for any common YAML file or CI provider, not just Travis.

**Comment by felixfbecker** [comment]
@JPinkney there are definitely still gaps in the JSON schema for AppVeyor and Travis, I hacked them together in a few hours. I don't think that is an argument agains this feature though - anyone can improve it online, and this is how the JSON IntelliSense for vscode works too.
What are the things that make it incompatible with autocomplete? I noticed autocomplete sometimes doesn't work, but isn't that something that should be fixed in the language server then (i.e. supporting all properties of jsonschema)?

**Comment by felixfbecker** [comment]
Did a PR here to improve the Travis schema: https://github.com/SchemaStore/schemastore/pull/374
For the deploy provider and Sonarcube addon, I would encourage you to contribute them.

**Comment by JPinkney** [comment]
For the appveyor schema the only thing that needs to be added is the [properties for the job](https://gist.github.com/JPinkney/a2ce9c6a04a72422e55c8b07844a763b#file-appveyor-json-L81) and it will work with both the yaml and json language servers. Thats the only thing I've found, everything else for that schema seems to work fine as far as I can see! The language servers are actually following jsonschema it was just missing that properties field and we are good to go (I'll do a PR for that in a few minutes)

**Pull request closed without merging**
