### PR TITLE
Use yarn on GH action, upload vsix artifact

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?

Use yarn on GH action, upload vsix artifact

### CODE REVIEW

**Comment by fbricon** [comment]
generated vsix works for me

**Review by fbricon — APPROVED** [review]

**Review by JPinkney — COMMENTED** [review]
Not sure if I entirely understand all the changes so I'm just double checking. It looks like this github action is supposed to run on pull requests (as well as pushes to master). Doesn't this mean that every pull request will product a vsix and then upload it?

**Comment by fbricon** [comment]
yes, so anyone can test it, see https://github.com/redhat-developer/vscode-yaml/actions/runs/863538797 for instance (artifact at the bottom of the page)

**Comment by JPinkney** [comment]
Ah that makes sense. I thought the uploaded artifact was going to automatically be added to the releases page for some reason and just wanted to double check. That makes sense though

**Review by JPinkney — APPROVED** [review]

**Review by joshuawilson — APPROVED** [review]

**Pull request merged**
