### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by JuriBurakov**

### CODE REVIEW

**Comment by evidolob** [comment]
@JuriBurakov Can you provide meaningful title for PR and fill PR's description?

**Comment by JPinkney** [comment]
It looks like they're just spamming this on multiple different repositories, I don't think any of it is needed

**Comment by joshuawilson** [comment]
I suggest we close this then and @JuriBurakov can reopen it if he wants to explain the PR.

**Comment by JPinkney** [comment]
Agreed, I'll close this PR then

**Pull request closed without merging**
