### PR TITLE
Xlr schema

### PR DESCRIPTION
**Pull request by paulvanderende**

### CODE REVIEW

**Comment by JPinkney** [comment]
Hi, uhhh, i'm guessing this PR was actually meant to just be in its own repo?

**Comment by paulvanderende** [comment]
yes, sorry

**Comment by JPinkney** [comment]
No worries, I've made the same mistake before too

**Comment by fbricon** [comment]
@paulvanderende you can probably create an extension on top of vscode-yaml, instead of forking it. It might need some changes to vscode-yaml to allow for more extensibility, but I think that's a better approach

**Pull request closed without merging**
