### PR TITLE
Add GitHub Action to build PR

### PR DESCRIPTION
**Pull request by evidolob**
This Action only build PR, for three main OS.

### CODE REVIEW

**Comment by joshuawilson** [comment]
Do we still need Travis running for PRs if we are going to use github actions?

**Comment by evidolob** [comment]
At the end, we do not need Travis, but now it is used for release vscode-yaml to npm registry. I'm not sure why, maybe @gorkem can answer? I keep travis only for that release.

**Comment by joshuawilson** [comment]
Can we turn it off for PRs? But keep it for release?

**Comment by gorkem** [comment]
Looks like there is a test failing on wins.

**Comment by evidolob** [comment]
> Looks like there is a test failing on wins.

Yes, I'm looking on it

**Comment by evidolob** [comment]
> Can we turn it off for PRs? But keep it for release?

Yes I think, but I still don't know why we release vscode extension on npm registry. So maybe we can remove travis at all?
@gorkem WDYT?

**Comment by JPinkney** [comment]
I couldn't find out why it was done originally but people have asked for it to be updated before: https://github.com/redhat-developer/vscode-yaml/issues/283

**Comment by evidolob** [comment]
OK, then, will keep travis for release, and remove it from building PR.

I have plan to move release to GH Actions as separate workflow, in separate PR.

**Comment by joshuawilson** [comment]
Maybe we need travis on the PR so we know that the release will pass?
As for npm, I think it might be to provide types since you can't get that from the API.

**Pull request merged**
